# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Zip
version:      1.17_02
version_from: lib/Archive/Zip.pm
installdirs:  site
requires:
    Carp:                          0
    Compress::Zlib:                1.14
    Data::Dumper:                  0
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0.80
    File::Temp:                    0
    Getopt::Std:                   0
    IO::File:                      0
    IO::Handle:                    0
    IO::Seekable:                  0
    Test::More:                    0.42
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
